#!/usr/bin/python3
import os
import shutil
from pathlib import Path
from datetime import datetime

rapydo = shutil.which("rapydo") is not None

if rapydo:
    configfile = Path("/etc/check_mk/backup.cfg")

    if not configfile.exists():
        print('1 "RAPyDo Backup" - Configuration file not found')
    else:
        with open(configfile, "r") as f:
            for line in f:
                line = line.strip()
                if " " not in line:
                    continue
                days, p = line.split(" ")
                try:
                    days = int(days)
                except Exception:
                    print(f'1 "RAPyDo Backup" - Wrong configuration file, {days} is not a number')
                    days = 1

                hours = days * 24

                backup_path = Path(p)
                if not backup_path.exists():
                    print(f'2 "RAPyDo Backup {backup_path.stem}" - {backup_path} not found')
                else:
                    last_backup = -1
                    for backup_file in backup_path.iterdir():
                        last_mod = datetime.fromtimestamp(backup_file.stat().st_mtime)
                        t = round((datetime.now() - last_mod).total_seconds() / 3600)
                        if last_backup == -1 or last_backup > t:
                            last_backup = t

                    if last_backup == -1:
                        print(f'2 "RAPyDo Backup {backup_path.stem}" - Last backup not found')
                    else:
                        w = round(hours * 1.5)
                        c = round(w * 2)
                        print(f'P "RAPyDo Backup {backup_path.stem}" hours={last_backup};{w};{c};0; Last backup executed {last_backup} hour(s) ago')

rsnapshot = shutil.which("rsnapshot") is not None

if rsnapshot:

    last_backup = -1

    configtest = os.popen("rsnapshot configtest").read().strip()
    if configtest != "Syntax OK":
        print('2 "Rsnapshot syntax" - Configtest failed configuration file verification')

    else:
        conf = "/etc/rsnapshot.conf"

        snapshot_root = None
        with open(conf, "r") as f:
            for line in f:
                if line.startswith("snapshot_root"):
                    line = line.strip()
                    # With python 3.9 => removeprefix
                    snapshot_root = line[13:].strip()

        if not snapshot_root:
            print('2 "Rsnapshot syntax" - The configuration is missing an entry for snapshot_root')
        else:
            snapshot_path = Path(snapshot_root)
            if not snapshot_path.exists():
                print(f'2 "Rsnapshot syntax" - {snapshot_path} path does not exist')
            else:
                snapshot_path = snapshot_path.joinpath("daily.0")
                if not snapshot_path.exists():
                    print(f'2 "Rsnapshot syntax" - {snapshot_path} path does not exist')
                else:
                    print('0 "Rsnapshot syntax" - Configtest successfully verified the configuration file')
                    last_mod = datetime.fromtimestamp(snapshot_path.stat().st_mtime)
                    last_backup = round((datetime.now() - last_mod).total_seconds() / 3600)

    if last_backup == -1:
        print('2 "Rsnapshot Backup" - Last backup not found')
    else:
        print(f'P "Rsnapshot Backup" hours={last_backup};36;72;0; Last backup executed {last_backup} hour(s) ago')

